# Generated by Django 5.0.6 on 2026-03-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('is_consolidated', models.BooleanField(default=True)),
                ('equity_capital', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('reserves', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('borrowings', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('other_liabilities', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('fixed_assets', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('cwip', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('other_assets', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'stocks_balance_sheet',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('is_consolidated', models.BooleanField(default=True)),
                ('cash_from_operating', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('cash_from_investing', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('cash_from_financing', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'stocks_cash_flow',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('BOTH', 'NSE & BSE')], default='NSE', max_length=10)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=12)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_change', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('day_change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stocks_stock',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('debtor_days', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('inventory_days', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('days_payable', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('cash_conversion_cycle', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('working_capital_days', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roce_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pe_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('current_ratio', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roe_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'stocks_financial_ratio',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_symbol', models.CharField(db_index=True, max_length=20)),
                ('peer_name', models.CharField(max_length=200)),
                ('is_current', models.BooleanField(default=True)),
                ('cmp', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('pe_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('div_yield', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('np_qtr', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('qtr_profit_var_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('sales_qtr', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('qtr_sales_var_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roce', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'stocks_peer',
            },
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('ttm', 'Trailing 12 Months')], default='annual', max_length=10)),
                ('is_consolidated', models.BooleanField(default=True)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('opm_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('other_income', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('profit_before_tax', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('tax_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dividend_payout_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'stocks_profit_loss',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('is_consolidated', models.BooleanField(default=True)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('opm_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('other_income', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('profit_before_tax', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('tax_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'stocks_quarterly_result',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='ShareholdingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('promoter_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dii_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fii_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('public_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('others_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'stocks_shareholding',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('interval', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day'), ('1wk', '1 Week'), ('1mo', '1 Month')], default='1d', max_length=5)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'stocks_price',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompanyOverview',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='overview', serialize=False, to='stocks.stock')),
                ('pe_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('div_yield_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roce_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('roe_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('debt_to_equity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('sales_cagr_10y', models.CharField(blank=True, max_length=10)),
                ('profit_cagr_10y', models.CharField(blank=True, max_length=10)),
                ('stock_cagr_10y', models.CharField(blank=True, max_length=10)),
                ('roe_avg_10y', models.CharField(blank=True, max_length=10)),
                ('about', models.TextField(blank=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('chairman', models.CharField(blank=True, max_length=100)),
                ('md_ceo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'stocks_company_overview',
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='idx_stock_symbol'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='idx_stock_sector'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['industry'], name='idx_stock_industry'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['name'], name='idx_stock_name'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='financialratio',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='peer',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='profitloss',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='quarterlyresult',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_results', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='shareholdingpattern',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholding', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('stock', 'period', 'is_consolidated')},
        ),
        migrations.AddIndex(
            model_name='balancesheet',
            index=models.Index(fields=['stock', 'period'], name='idx_bs_stock_period'),
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('stock', 'period', 'is_consolidated')},
        ),
        migrations.AddIndex(
            model_name='financialratio',
            index=models.Index(fields=['stock', 'period'], name='idx_ratio_stock_period'),
        ),
        migrations.AlterUniqueTogether(
            name='financialratio',
            unique_together={('stock', 'period')},
        ),
        migrations.AddIndex(
            model_name='peer',
            index=models.Index(fields=['stock', 'peer_symbol'], name='idx_peer_stock_symbol'),
        ),
        migrations.AddIndex(
            model_name='profitloss',
            index=models.Index(fields=['stock', 'period'], name='idx_pl_stock_period'),
        ),
        migrations.AlterUniqueTogether(
            name='profitloss',
            unique_together={('stock', 'period', 'is_consolidated')},
        ),
        migrations.AlterUniqueTogether(
            name='quarterlyresult',
            unique_together={('stock', 'period', 'is_consolidated')},
        ),
        migrations.AlterUniqueTogether(
            name='shareholdingpattern',
            unique_together={('stock', 'period')},
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock', 'timestamp', 'interval'], name='idx_price_stock_ts_interval'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['timestamp'], name='idx_price_timestamp'),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('stock', 'timestamp', 'interval')},
        ),
    ]
