# Generated by Django 5.0.6 on 2026-03-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=5, unique=True)),
                ('is_open', models.BooleanField(default=False)),
                ('opens_at', models.TimeField(default='09:15:00')),
                ('closes_at', models.TimeField(default='15:30:00')),
                ('next_open', models.DateTimeField(blank=True, null=True)),
                ('status_message', models.CharField(blank=True, max_length=100)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Status',
                'db_table': 'market_status',
            },
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('NIFTY50', 'Nifty 50'), ('SENSEX', 'BSE Sensex'), ('BANKNIFTY', 'Bank Nifty'), ('NIFTYMID50', 'Nifty Midcap 50'), ('NIFTYIT', 'Nifty IT')], db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('exchange', models.CharField(default='NSE', max_length=5)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('day_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Market Index',
                'verbose_name_plural': 'Market Indices',
                'db_table': 'market_index',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='idx_index_symbol')],
            },
        ),
        migrations.CreateModel(
            name='IndexPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('interval', models.CharField(choices=[('1m', '1m'), ('5m', '5m'), ('1h', '1h'), ('1d', '1d')], default='1d', max_length=5)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.marketindex')),
            ],
            options={
                'db_table': 'market_index_price',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['index', 'timestamp'], name='idx_idxprice_idx_ts')],
                'unique_together': {('index', 'timestamp', 'interval')},
            },
        ),
    ]
